// <auto-generated />
using System;
using DynamicDbManager.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicDbManager.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522084900_EditedRows")]
    partial class EditedRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicDbManager.Server.Models.ColumnDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int?>("Precision")
                        .HasColumnType("int");

                    b.Property<int?>("Scale")
                        .HasColumnType("int");

                    b.Property<Guid>("TableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TableId", "ColumnName")
                        .IsUnique();

                    b.ToTable("ColumnDefinitions");
                });

            modelBuilder.Entity("DynamicDbManager.Server.Models.FileAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("FileData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("DynamicDbManager.Server.Models.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OnDelete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OnUpdate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ParentColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentTableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferencedColumnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferencedTableId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentColumnId");

                    b.HasIndex("ParentTableId");

                    b.HasIndex("ReferencedColumnId");

                    b.HasIndex("ReferencedTableId");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("DynamicDbManager.Server.Models.TableDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModalColumnsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SchemaName", "TableName")
                        .IsUnique();

                    b.ToTable("TableDefinitions");
                });

            modelBuilder.Entity("DynamicDbManager.Server.Models.ColumnDefinition", b =>
                {
                    b.HasOne("DynamicDbManager.Server.Models.TableDefinition", "Table")
                        .WithMany("Columns")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DynamicDbManager.Server.Models.Relationship", b =>
                {
                    b.HasOne("DynamicDbManager.Server.Models.ColumnDefinition", "ParentColumn")
                        .WithMany()
                        .HasForeignKey("ParentColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DynamicDbManager.Server.Models.TableDefinition", "ParentTable")
                        .WithMany("ParentRelationships")
                        .HasForeignKey("ParentTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DynamicDbManager.Server.Models.ColumnDefinition", "ReferencedColumn")
                        .WithMany()
                        .HasForeignKey("ReferencedColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DynamicDbManager.Server.Models.TableDefinition", "ReferencedTable")
                        .WithMany("ReferencedRelationships")
                        .HasForeignKey("ReferencedTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentColumn");

                    b.Navigation("ParentTable");

                    b.Navigation("ReferencedColumn");

                    b.Navigation("ReferencedTable");
                });

            modelBuilder.Entity("DynamicDbManager.Server.Models.TableDefinition", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("ParentRelationships");

                    b.Navigation("ReferencedRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
